### ISSUE TITLE
Cyclic Complexity also applying to auto-generated files

### ISSUE THREAD

**Issue by jaybarden** [Capgemini/dotnet-code-analysis#20]
And thus breaking the build...

**Comment by jaybarden** [comment]
Hi Ekhor,
Does your recent PR resolve this issue? - forgot to check when I was reviewing but as it was for auto-generated, it may well do.
Thanks in advance.
Jay

**Comment by realekhor** [comment]
hi Jay,
Thank you. yes i tested this on the cyclic complexity analyzer as well :)

regards,
ekhor

**Comment by realekhor** [comment]
i added one unit test here (https://github.com/Capgemini/dotnet-code-analysis/blob/master/Capgemini.CSharpCodeAnalysis/Capgemini.CodeAnalysis.CoreAnalysers/Tests/Capgemini.CodeAnalysis.CoreAnalysers.Test/Analyzers/MethodComplexityAnalyzerTests.cs )


        [TestMethod]
        public void IgnoresGneratedSourceCode()
        {
            var test = CommonConstants.AutoGeneratedCodeHeader + @"
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Threading.Tasks;
    using System.Diagnostics;
    namespace Test0
    {
        public class TypeName
        {              
            public void DoStuff(int year, string message,int input)
            {   
                if(!string.IsNullOrWhiteSpace(message))
                {
                    var variable1 = 20;
                   var processedMessage = new StringBuilder();
                    if(input > variable1)
                    {
                        processedMessage.AppendLine( ""Maybe not hello world!"");
                    }
                    else if(input < variable1)
                    {
                       processedMessage.AppendLine( message + ""Some other interesting message!"");
                    }
                    else
                    {
                         processedMessage.AppendLine( ""Hello world"" + message);
                    }
                    var leapYear =false; 
                    var date = new DateTime(year,3,1);
                    var lastDayOfFebruaryForThisYear = date.AddDays(-1);
                    if (lastDayOfFebruaryForThisYear.Day>28)
                    {
                        leapYear=true;
                    }
                    var curDate = DateTime.UtcNow;
                    if (curDate.Month == 2 && curDate.Day > 20)
                    {
                        processedMessage.AppendLine(""This is some month!"");
                    }
                    else if (leapYear && curDate.Month > 6 && && curDate.Mont < 8 && curDate.Day > 10 && curDate.Day < 31)
                    {
                        processedMessage.AppendLine(""This is getting exciting!"");
                    }
                    else if (curDate.Month == 12 && && curDate.Day == 25 && curDate.UtcNow.DayOfWeek== DayOfWeek.Monday)
                    {
                        processedMessage.AppendLine(""This is Christmas is on Monday!"");
                    }
            }
        }
    }
}";
            
            VerifyCSharpDiagnostic(test);
        }

**Comment by jaybarden** [comment]
Issue is resolved, this should have been closed at the time. My bad.
